pydjango/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

# movies/
# movies/1/details
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.details, name='detail')
]

pydjango/vidly/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from . import views
from api.models import MovieResource

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    url(r'^admin/', admin.site.urls),
    path('api/', include(movie_resource.urls)),
    path('movies/', include('movies.urls')),
]

pydjango/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']

pydjango/movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

pydjango/api/views.py
from django.shortcuts import render

# Create your views here.

pydjango/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.


def index(request):
    # SELECT * FROM movies_movie
    movies = Movie.objects.all()

    # SELECT * FROM movies_movie WHERE ...
    # Movie.objects.filter(release_year=1984)
    # Movie.objects.get(id=1)

    return render(request, 'movies/index.html', {'movies': movies})


def details(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/details.html', {'movie': movie})

pydjango/vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

pydjango/movies/templates/movies/details.html
{% extends 'base.html' %} {% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Stock</dt>
        <dd>{{ movie.number_in_stock }}</dd>
    </dl>
{% endblock %}

pydjango/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
                <tr>
                    <td>
                        <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                    </td>
                    <td>{{ movie.genre }}</td>
                    <td>{{ movie.number_in_stock }}</td>
                    <td>{{ movie.daily_rate }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

pydjango/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Vidly</title>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Vidly</a>
    </nav>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

pydjango/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}